name: Auto Fetch Sports Streams Data

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ১ ঘণ্টা পর পর চলবে
  workflow_dispatch: # Manual Run করার বাটন দেবে

# permissions যোগ করুন
permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run scraper script
      run: python fetch_data.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update streaming data" && git push)
